basePath: /api/v1/
definitions:
  server_side.Movie:
    properties:
      director:
        type: string
      done:
        type: boolean
      id:
        type: integer
      title:
        type: string
      year:
        type: integer
    type: object
host: localhost:8081
info:
  contact: {}
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://localhost:8081/terms/
  title: to-do-Movie API
  version: "1.0"
paths:
  /movies:
    get:
      consumes:
      - application/json
      description: show all movies
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/server_side.Movie'
            type: array
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/server_side.Movie'
      summary: show all movies
      tags:
      - GET All Movies
    post:
      consumes:
      - application/json
      description: create movie
      produces:
      - application/json
      responses:
        "200":
          description: No Content
        "404":
          description: No Content
      summary: create movie
      tags:
      - POST Movie
  /movies/id/{id}:
    delete:
      consumes:
      - application/json
      description: delete movie by Id
      produces:
      - application/json
      responses:
        "200":
          description: No Content
        "404":
          description: No Content
      summary: delete movie by Id
      tags:
      - DELETE Movie by Id
    get:
      consumes:
      - application/json
      description: show movie by Id
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/server_side.Movie'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/server_side.Movie'
      summary: show movie by Id
      tags:
      - GET Movie by Id
    put:
      consumes:
      - application/json
      description: update movie by Id
      produces:
      - application/json
      responses:
        "200":
          description: No Content
        "404":
          description: No Content
      summary: update movie by Id
      tags:
      - UPDATE Movie by Id
swagger: "2.0"
